apiVersion: zw.zw.com/v1
kind: Zwdemo
metadata:
  labels:
    app.kubernetes.io/name: zwdemo
    app.kubernetes.io/instance: zwdemo-sample
    app.kubernetes.io/part-of: operator4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator4
  name: zwdemo-sample
spec:
  # TODO(user): Add fields here
